# Generated by Django 4.0.5 on 2022-07-04 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_link', models.URLField(editable=False, verbose_name='Short link')),
                ('long_link', models.URLField(verbose_name='Long link')),
                ('last_visited_date', models.DateField(auto_now=True, verbose_name='last visited')),
                ('visit_count', models.PositiveBigIntegerField(default=0, editable=False, verbose_name='visit count')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'long_link', 'short_link')},
            },
        ),
        migrations.CreateModel(
            name='AnalyticByDateTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.link')),
            ],
        ),
        migrations.CreateModel(
            name='Analytic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.JSONField(default=dict)),
                ('os', models.JSONField(default=dict)),
                ('browser', models.JSONField(default=dict)),
                ('refer', models.JSONField(default=dict)),
                ('country', models.JSONField(default=dict)),
                ('link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.link')),
            ],
        ),
    ]
