# Generated by Django 4.0.5 on 2022-07-26 15:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_link', models.URLField(editable=False, verbose_name='Short link')),
                ('long_link', models.TextField(max_length=1000, validators=[django.core.validators.URLValidator], verbose_name='Long link')),
                ('last_visited_date', models.DateTimeField(default=None, editable=False, null=True, verbose_name='last visited')),
                ('visit_count', models.PositiveBigIntegerField(default=0, editable=False, verbose_name='visit count')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticByDateTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.link')),
            ],
        ),
        migrations.CreateModel(
            name='Analytic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.JSONField(default=dict)),
                ('os', models.JSONField(default=dict)),
                ('browser', models.JSONField(default=dict)),
                ('referer', models.JSONField(default=dict)),
                ('country', models.JSONField(default=dict)),
                ('link', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='api.link')),
            ],
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['owner'], name='api_link_owner_i_816afa_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['short_link'], name='api_link_short_l_a72219_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticbydatetime',
            index=models.Index(fields=['link', 'date'], name='api_analyti_link_id_b11e8c_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticbydatetime',
            index=models.Index(fields=['link'], name='api_analyti_link_id_0cd8e3_idx'),
        ),
        migrations.AddIndex(
            model_name='analytic',
            index=models.Index(fields=['link'], name='api_analyti_link_id_3fb552_idx'),
        ),
    ]
