# Generated by Django 4.0.5 on 2022-07-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='long_link',
            field=models.TextField(verbose_name='Long link'),
        ),
    ]
