# Generated by Django 4.0.5 on 2022-07-02 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.JSONField(default=dict)),
                ('os', models.JSONField(default=dict)),
                ('browser', models.JSONField(default=dict)),
                ('refer', models.JSONField(default=dict)),
                ('country', models.JSONField(default=dict)),
                ('city', models.JSONField(default=dict)),
                ('date_time', models.JSONField(default=dict)),
                ('link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.link')),
            ],
        ),
    ]
