# Generated by Django 4.0.5 on 2022-07-05 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analytic',
            old_name='refer',
            new_name='referer',
        ),
        migrations.AddField(
            model_name='link',
            name='date_created',
            field=models.DateField(default=datetime.date(2022, 7, 5)),
        ),
    ]
