# Generated by Django 4.0.5 on 2022-07-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='analytic',
            index=models.Index(fields=['link'], name='api_analyti_link_id_3fb552_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticbydatetime',
            index=models.Index(fields=['link', 'date'], name='api_analyti_link_id_b11e8c_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticbydatetime',
            index=models.Index(fields=['link'], name='api_analyti_link_id_0cd8e3_idx'),
        ),
    ]
