# Generated by Django 4.0.5 on 2022-07-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_link_long_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='last_visited_date',
            field=models.DateField(default=None, editable=False, null=True, verbose_name='last visited'),
        ),
    ]
