# Generated by Django 4.0.5 on 2022-07-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_link_long_link'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['short_link'], name='api_link_short_l_a72219_idx'),
        ),
    ]
