# Generated by Django 4.0.5 on 2022-06-29 20:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_alter_link_long_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='short_link',
            field=models.URLField(editable=False, verbose_name='Short link'),
        ),
        migrations.AlterUniqueTogether(
            name='link',
            unique_together={('owner', 'long_link', 'short_link')},
        ),
    ]
