# Generated by Django 4.0.5 on 2022-07-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_analytic_api_analyti_link_id_3fb552_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['owner'], name='api_link_owner_i_816afa_idx'),
        ),
    ]
