# Generated by Django 4.0.5 on 2022-07-26 14:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_link_api_link_short_l_a72219_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2022, 7, 26, 14, 27, 49, 725919, tzinfo=utc)),
        ),
    ]
