# Generated by Django 4.0.5 on 2022-07-29 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_link_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalRedirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.BigIntegerField()),
            ],
        ),
    ]
