# Generated by Django 4.0.5 on 2022-07-06 16:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_alter_link_date_created'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='link',
            unique_together={('owner', 'short_link')},
        ),
        migrations.AlterField(
            model_name='link',
            name='long_link',
            field=models.TextField(validators=[django.core.validators.URLValidator], verbose_name='Long link'),
        ),
    ]
