# Generated by Django 4.0.5 on 2022-07-06 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_link_long_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='long_link',
            field=models.TextField(validators=[django.core.validators.URLValidator], verbose_name='Long link'),
        ),
    ]
