# Generated by Django 4.0.5 on 2022-07-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_link_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='last_visited_date',
            field=models.DateTimeField(default=None, editable=False, null=True, verbose_name='last visited'),
        ),
    ]
